"""add suppression list

Revision ID: 6cf00f7cb7ba
Revises: 3b0d3add881e
Create Date: 2026-07-23 16:39:56.166868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf00f7cb7ba'
down_revision: Union[str, None] = '3b0d3add881e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_list_contact'), 'suppression_list', ['contact'], unique=False)
    op.create_index('ix_suppression_lookup', 'suppression_list', ['project_id', 'contact', 'channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suppression_lookup', table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_contact'), table_name='suppression_list')
    op.drop_table('suppression_list')
    # ### end Alembic commands ###
