"""add_smtp_fields_to_projects

Revision ID: eb2d61d60657
Revises: 6cf00f7cb7ba
Create Date: 2026-07-24 11:14:32.640983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2d61d60657'
down_revision: Union[str, None] = '6cf00f7cb7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('smtp_host', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('smtp_port', sa.Integer(), nullable=False, server_default='587'))
    op.add_column('projects', sa.Column('smtp_username', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('smtp_password', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('smtp_from_address', sa.String(length=300), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'smtp_from_address')
    op.drop_column('projects', 'smtp_password')
    op.drop_column('projects', 'smtp_username')
    op.drop_column('projects', 'smtp_port')
    op.drop_column('projects', 'smtp_host')
    # ### end Alembic commands ###
